name: Auto Update
on:
  push:
    paths:
      - 'images/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: node make_html.js
      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add index.html
          git commit -m "update" || exit 0
          git push
